### ISSUE TITLE
Extend support of firebase/php-jwt with version 6 branch

### ISSUE THREAD

**Issue by pixelfantasy** [imbo/behat-api-extension#120]
Hello,

we had to update some of our packages to the latest version because of some Synk findings. Now we stumpled upon an incompatibility regarding the package composition. Would it be possible to extend your `composer.json` like shown below or are there any known issues with version 6 of `firebase/php-jwt`?

    "require": {
        "firebase/php-jwt": "^5.2 || ^6.0",
    }

Vulnerability details can be found here. It seems that every version below 6 has a CVSS score with 7.5 (high).
https://security.snyk.io/vuln/SNYK-PHP-FIREBASEPHPJWT-2434829

**Comment by jawira** [comment]
Yes please, I also can't update my project's dependencies because of this.

**Comment by chris-archer-whisky** [comment]
Hi, is there any update on this we also need this issue fixed.

**Comment by christeredvartsen** [comment]
#125

**Comment by pixelfantasy** [comment]
Thanks for upgrading dependencies
