### ISSUE TITLE
Php 7

### ISSUE THREAD

**Issue by kevin-lot** [imbo/behat-api-extension#17]
My composer don't want install your package because I have php 7 installed.
"imbo/behat-api-extension v1.0.4 requires php >=5.6 -> your PHP version (7.0.8...."

Do your package run under this version of PHP ?

**Comment by christeredvartsen** [comment]
It should. Travis-CI successfully installs the package and runs tests: https://travis-ci.org/imbo/behat-api-extension/jobs/174724705.

Can you please paste the complete message from composer? And what does `php -v` say on your system?

**Comment by christeredvartsen** [comment]
Verified that it can be installed under PHP-7 in Docker now, using the following Dockerfile ([gist here](https://gist.github.com/christeredvartsen/d889515269e9027f6450267061dee888)):

```Dockerfile
FROM ubuntu:yakkety
RUN apt-get update && apt-get install -y php7.0 php-mbstring php-dom composer zip
RUN php -v
RUN echo '{"require":{"imbo/behat-api-extension":"^1.0"}}' > composer.json
RUN composer install
```

Output of interest from building (`docker build -t install-behat-api-extension-on-php7 .`):

    Step 3 : RUN php -v
    PHP 7.0.8-3ubuntu3 (cli) ( NTS )
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
        with Zend OPcache v7.0.8-3ubuntu3, Copyright (c) 1999-2016, by Zend Technologies
    ...
    Step 5 : RUN composer install
    ...
      - Installing imbo/behat-api-extension (v1.0.4)
    Downloading: 100%
    ...
    Writing lock file
    Generating autoload files
    
The package (`v1.0.4`) is installed successfully. If you provide me with the contents of your `composer.json` file I can probably help out some more. Closing this issue for now. Feel free to re-open if you feel this package is still to blame.
