### ISSUE TITLE
Verify array of objects

### ISSUE THREAD

**Issue by oqq** [imbo/behat-api-extension#40]
Given the following response body

```json
{
    "some_value": true,
    "other_value": "foo bar",
    "array_of_objects": [
        {
            "value_1": 123,
            "value_2": 456,
        },
        {
            "value_1": 75577,
            "value_2": 12456,
        },
    ]
}
```

I need a way to verify the structure of all objects in `array_of_objects`.
The amount of objects in `array_of_objects` is undefined.

My current approach is
```json
{
    "array_of_objects": "@atLeast(1)",
    "array_of_objects[0]": {
        "value_1": "<re>/^[0-9]+$/</re>",
        "value_2": "<re>/^[0-9]+$/</re>",
    }
}
```

But this only tests the first object.
I like to have a option to test all objects in `array_of_objects` against a defined structure.

**Comment by christeredvartsen** [comment]
Added to the newly created `v2.0` milestone. When other tasks have been done I can come up with a suggestion to an implementation for this.

**Comment by oqq** [comment]
Oh nice .. sounds good! Thanks! 🍺

**Comment by oqq** [comment]
This would be similar to JsonPath and should be preferred way, sure!

**Comment by christeredvartsen** [comment]
I haven't looked too much into the possibilities with JsonPath yet, but is the problem explained in this issue solvable with JsonPath, or would this be a separate issue?

**Comment by oqq** [comment]
I am not sure about that. With JsonPath there are simliar ways to solve your "functions". But you have always to define a path to get a single value or an array of values. Maybe there is no way to define complete structures at once how with your approach.

I would use jmespath like this:
```json
{
    "path[*].to.some.object.in_response": {
        "value1": "@type(int)",
        "value2": "@type(string)"
    },
    "other_path.to_value": "exact_this_value"
}
```

or similar, maybe some chars not possible as key.
