### ISSUE TITLE
Add 'any' as a variable type in ArrayContainsComparator/Matcher/VariableType.php for checking JSON structure

### ISSUE THREAD

**Issue by stuart-gill** [imbo/behat-api-extension#83]
Hi, I'm trying to write functional tests for an API. I want to test the JSON response body of certain calls, which will sometimes have null values and sometimes string or integer. I'm not using a test database, so the responses change over time. For example, if I were testing this response--

"data" : {
        "age_18_24_percent": 12,
        "age_18_34_percent": 22,
        "age_25_29_percent": 5,
        "age_30_34_percent": null,
        "age_35_39_percent": 3
}

I would want either integer OR null data types to be accepted. Really, I just want to test that the keys exist, I don't care what the values are. I propose testing this response like this:

And the response body contains JSON:
"""
"data" : {
        "age_18_24_percent": "@variableType(any)",
        "age_18_34_percent": "@variableType(any)",
        "age_25_29_percent": "@variableType(any)",
        "age_30_34_percent": "@variableType(any)",
        "age_35_39_percent": "@variableType(any)"
}
"""

This change would only require adding "any" to valid types and adding the line 
        if ($expectedType === 'any') {
            return;
        }
around line 53 in Matcher/VariableTypes.php. 

Another option would be to remove the code in Matcher/RegExp that restricts you to checking only strings, ints and doubles. 

Thank you very much for writing and maintaining this extension, it's much appreciated!

**Comment by christeredvartsen** [comment]
Sounds like a good addition. I can add support for `any`, as well as support for specifying multiple types, for instance: `@variableType(int|null)`.

**Comment by christeredvartsen** [comment]
The support for `any` has been added to the `dev-issue/83-multile-variable-types` branch (https://github.com/imbo/behat-api-extension/pull/84). I will add support for multiple types as well before creating a release. If you want to test the `any`-keyword feel free to require the branch in your `composer.json`.

**Comment by christeredvartsen** [comment]
@stuart-gill Support for multiple types have also been added.

**Comment by christeredvartsen** [comment]
`v2.3.0` has just been released, which includes the features mentioned above.
